version: '3'

services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/help-me'
      - 'box:/box'
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - box:/box

volumes:
  postgres:
  box: